# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Build
on:
  workflow_call:
    secrets:
      github-token:
        description: |
          The token to use for making authenticated requests to GitHub APIs.
        required: true
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - id: checkout-repository
        name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{secrets.github-token || secrets.GITHUB_TOKEN}}
          lfs: true
      - id: setup-nodejs
        name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: npm
          cache-dependency-path: ./package-lock.json
          token: ${{secrets.github-token || secrets.GITHUB_TOKEN}}
      - id: install-dependencies
        name: Install dependencies
        run: npm install
      - id: build
        name: Build
        run: npm run build:ci
      - id: package
        name: Package
        run: npm run package:ci
      - id: upload-artifacts
        name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: extension-vsix
          path: '*.vsix'
          if-no-files-found: error
          compression-level: 0
