# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: On Push
on:
  push:
jobs:
  test:
    name: Test
    uses: ./.github/workflows/test.yaml
    secrets:
      github-token: ${{secrets.GITHUB_TOKEN}}
  lint:
    name: Lint
    uses: ./.github/workflows/lint.yaml
    secrets:
      github-token: ${{secrets.GITHUB_TOKEN}}
  build:
    name: Build
    uses: ./.github/workflows/build.yaml
    secrets:
      github-token: ${{secrets.GITHUB_TOKEN}}
